[build]
  command = "npm run build"
  publish = "build/client"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200
  force = false
